### ISSUE TITLE
Create an 18F channel

### ISSUE THREAD

**Issue by RobertLRead** [18F/ifgovthenthat#11]
I imagine that a trigger would be an 18F blogpost for example.

**Comment by gbinal** [comment]
Huh - nice.  I wonder if there's the ability to make unofficial ifttt channels.  

G

**Comment by webmaven** [comment]
I think you can just use a generic RSS or Atom feed.

**Comment by tdlowden** [comment]
For this type of thing, I'd agree with webmaven. Use an RSS, and then publicly post an example link to recipes that make use of the RSS. 18F RSS to email is prob most appropriate.
