### ISSUE TITLE
Fix Codecademy link

### ISSUE THREAD

**Issue by tdlowden** [18F/ifgovthenthat#14]
The current link goes to the wrong spot.

They omit the "a" in academy: http://www.codecademy.com/

**Comment by gbinal** [comment]
Hey Tim, can confirm where you mean?  (Always good to include a link or screenshot.)  

I'm seeing a link to codeacademy.com in the 2nd bullet on http://18f.github.io/ifgovthenthat/ but it appears to be correct.  Of course, I'm happy to show you how to make the edit as a pull request.  ;)

**Comment by tdlowden** [comment]
Sorry for lack of precision there. You are correct. Second bullet on the page. it goes to codeAcademy.com (which redirects to some other site), rather than codecademy.com.

![screen shot 2015-03-02 at 10 11 54 pm](https://cloud.githubusercontent.com/assets/6556888/6455970/76a486b0-c129-11e4-86aa-26dac5ba152e.png)

**Comment by tdlowden** [comment]
PR submitted
