### ISSUE TITLE
DO: a game changer?

### ISSUE THREAD

**Issue by tdlowden** [18F/ifgovthenthat#15]
I'm not sure what our ability to take advantage of DO is, but I think it opens up a whole new world of possibilities for gov channels. The DO button allows for on-demand execution of recipes for info that usually would be harder to access.

Examples: 
Rather than login to IRS to see tax refund status, hit the DO button to get SMS of the current status.
Hit the DO button to see have due date/amount of next student loan payment sent via SMS/email/whatever
DO button for application statuses of all kinds

**Comment by tdlowden** [comment]
DO: Current National Parks closures
DO: Acts of Congress in the last 24 hours

**Comment by leahbannon** [comment]
As far as I could tell, "DO" is just a list of suggested recipes. Is it something more?

**Comment by tdlowden** [comment]
Yes. It's a ton more. 

IF is passive. As in, trigger only happens when something happens. It might be out of your control. An RSS post, a Twitter post, leaving a radius, etc.

DO gives the user to make the thing happen on his/her own terms. IFTTT has rolled out a DO camera app, a DO note app and a DO button app. The DO button being the most interesting to me.

Example: If I set up an IF recipe to to post all my Instagram photos to Twitter, it sucks that if I have an Instagram photo, if even 1 of 100, that I DON'T want on Twitter. I have to go turn the recipe off. With DO camera, I take a photo and immediately choose which other channel I'd like it to post, each time.

With the DO button, you can do things like "send me my location (using iOS channel) via SMS" ON MY COMMAND of hitting the button. Then I can forward it to friends. This rather than opening Google maps app, dropping a pin, saving it, and sending it. You get what you want in one click.

Hundreds of thousands of people have checked their refund status in the last couple months. If we could set up an IRS channel that you authorize to IFTTT once, you could make a button recipe that you could use as "When I hit this button, send me my IRS refund status by SMS/email/whatever". This would save going to the site, logging in, and checking. It's immediate and on command, in my preferred delivery method.

This has serious, serious awesome potential.

**Comment by leahbannon** [comment]
Aaah ok... so it adds a generic trigger option (similar to how the Yo trigger worked before) for any action. We had originally planned to just focus on triggers instead of actions for the channels, but perhaps we should revisit. Worth discussing with IFTTT.

**Comment by tdlowden** [comment]
Agreed. In the top 10 sites in DAP year-round is the USCIS case status page. That is another example for which a DO button could make checking status infinitely easier.... and on mobile
