### ISSUE TITLE
Proposed change in description of repo.

### ISSUE THREAD

**Issue by melodykramer** [18F/ifgovthenthat#17]
Doing a general audit of all of our repos to make them clearer / more accessible for new hires and the public. Right now, the description of this repo is the same as the title.

I think it might be easier for new hires and members of the public to determine what IfGovThenThat does if the description reflects what is on the IGTT website: "Let's promote government open data by designing clever uses for government APIs." 

That way, anyone who comes across it [here](https://github.com/18F) will know exactly what the repo contains.

Mel

**Comment by leahbannon** [comment]
:+1: adding
