### ISSUE TITLE
gh pages link should work

### ISSUE THREAD

**Issue by adelevie** [18F/ifgovthenthat#3]
currently gets:

```
Sorry this page does not exist =(
```

**Comment by adelevie** [comment]
Looks like this is being fixed https://github.com/18F/ifgovthenthat/commit/df754206806daf9d37a2cc2fdf8b4f43a2801ed3

**Comment by leahbannon** [comment]
page is working at 18f.github.io/ifgovthenthat - please reopen if that's not the issue
